
package coresy.userinterface;

import java.awt.event.ActionEvent;
import java.util.List;
import java.util.Map;
import java.util.HashMap;
import java.util.ArrayList;
import java.util.Collections;
import java.util.stream.Collectors;

import javax.swing.JOptionPane;

import coresy.AdminTemplate;
import coresy.AdvisorTemplate;
import coresy.CourseTemplate;
import coresy.StudentTemplate;
import coresy.JsonHandler;

public class AdminUI extends javax.swing.JFrame {

    public AdminUI(AdminTemplate admin, List<StudentTemplate> students, List<AdvisorTemplate> advisors,
            List<CourseTemplate> courses) {
        initComponents(admin, students, advisors, courses);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents(AdminTemplate admin, List<StudentTemplate> students, List<AdvisorTemplate> advisors,
            List<CourseTemplate> courses) {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        courseCodeLabel = new javax.swing.JLabel();
        courseCodeTextField = new javax.swing.JTextField();
        courseNameLabel = new javax.swing.JLabel();
        courseNameTextField = new javax.swing.JTextField();
        courseSeatsLabel = new javax.swing.JLabel();
        courseSeatsTextField = new javax.swing.JTextField();
        courseCridetsLabel = new javax.swing.JLabel();
        courseCreditsTextField = new javax.swing.JTextField();
        courseInstructorComboBox = new javax.swing.JComboBox<>();
        instructorLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        courseDesTextArea = new javax.swing.JTextArea();
        courseDescriptionLabel = new javax.swing.JLabel();
        addCourseButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        coursePrerequistisList = new javax.swing.JList<>();
        prerequistisLabel = new javax.swing.JLabel();
        courseScheduleLabel = new javax.swing.JLabel();
        courseDayComboBox = new javax.swing.JComboBox<>();
        startHourComboBox = new javax.swing.JComboBox<>();
        endHourComboBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        studentTotalLabel = new javax.swing.JLabel();
        courseTotalLabel = new javax.swing.JLabel();
        advisorsTotalLabel = new javax.swing.JLabel();
        studentTotalValueLabel = new javax.swing.JLabel();
        courseTotalValueLabel = new javax.swing.JLabel();
        advisorsTotalValueLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        userRoleLabel = new javax.swing.JLabel();
        roleComboBox = new javax.swing.JComboBox<>();
        firstNameLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        firstNameTextField = new javax.swing.JTextField();
        usernameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        addUserButton = new javax.swing.JButton();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        courseCodeLabel.setText("Course Code:");

        courseNameLabel.setText("Course Name:");

        courseSeatsLabel.setText("Course Seats:");

        courseCridetsLabel.setText("Course Credits:");

        Map<String, AdvisorTemplate> advisorMap = new HashMap<>();
        for (AdvisorTemplate advisor : advisors) {
            String advisordata = advisor.getFullName();
            courseInstructorComboBox.addItem(advisordata);
            advisorMap.put(advisordata, advisor);
        }

        /*
         * courseInstructorComboBox.setModel(
         * new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2",
         * "Item 3", "Item 4" }));
         */
        instructorLabel.setText("Instructor");

        courseDesTextArea.setColumns(20);
        courseDesTextArea.setRows(5);
        jScrollPane1.setViewportView(courseDesTextArea);

        courseDescriptionLabel.setText("Course Descpiption:");

        addCourseButton1.setText("Add Course");

        Map<String, CourseTemplate> courseMap = new HashMap<>();

        String[] courseStrings = new String[courses.size()];
        for (int i = 0; i < courses.size(); i++) {

            CourseTemplate course = courses.get(i);
            String courseData = course.getCourseName() + " - " + course.getCourseCode();
            // Assuming CourseTemplate has a getName() method to get the course name
            courseStrings[i] = courseData;
            courseMap.put(courseData, course);
        }
        coursePrerequistisList.setModel(new javax.swing.AbstractListModel<String>() {

            public int getSize() {
                return courseStrings.length;
            }

            public String getElementAt(int i) {
                return courseStrings[i];
            }
        });
        coursePrerequistisList.setVisibleRowCount(3);
        jScrollPane2.setViewportView(coursePrerequistisList);

        prerequistisLabel.setText("Prerequistis:");

        courseScheduleLabel.setText("Course Schedule:");

        courseDayComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[] { "sat", "sun", "mon", "tus", "wed", "thu", "fri" }));

        startHourComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[] { "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm" }));

        endHourComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(
                        new String[] { "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm" }));

        addCourseButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButton1ActionPerformed(evt);
            }

            private void addCourseButton1ActionPerformed(ActionEvent evt) {
                String newCousrsCode = courseCodeTextField.getText();
                for (CourseTemplate c : courses) {
                    if (c.getCourseCode().equals(newCousrsCode)) {
                        JOptionPane.showMessageDialog(null, "Course already exists");
                        return;
                    }
                }
                String selectedInstructor = (String) courseInstructorComboBox.getSelectedItem();
                AdvisorTemplate advisor = advisorMap.get(selectedInstructor);

                int[] index = coursePrerequistisList.getSelectedIndices();
                String[] prerequistis = new String[index.length];
                for (int i = 0; i < index.length; i++) {
                    prerequistis[i] = (String) coursePrerequistisList.getModel().getElementAt(index[i]);
                }
                List<CourseTemplate> selectedPreCourses = new ArrayList<>();
                for (String prerequisti : prerequistis) {
                    selectedPreCourses.add(courseMap.get(prerequisti));
                }
                String scheduleString = courseDayComboBox.getSelectedItem() + ":" + startHourComboBox.getSelectedItem()
                        + ">>" + endHourComboBox.getSelectedItem();
                /*
                 * String[] registeredCourseName = (String) coursePrerequistisList.getModel()
                 * .getElementAt(index);
                 */
                // CourseTemplate registeredINCourse = courseMap.get(registeredCourseName);

                CourseTemplate newCourse = new CourseTemplate(courseNameTextField.getText(), newCousrsCode,
                        courseDesTextArea.getText(), Integer.parseInt(courseSeatsTextField.getText()), advisor,
                        selectedPreCourses,
                        null, scheduleString, Integer.parseInt(courseCreditsTextField.getText()));
                courses.add(newCourse);
                boolean changeSaved = false;
                if (!changeSaved) {
                    JsonHandler.writeCoursesToJson(courses, "src/coresy/systemdata/courses.json");
                    JOptionPane.showMessageDialog(null, "Course Added");
                }

            }
        });
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(addCourseButton1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(courseSeatsLabel)
                                                                                        .addComponent(
                                                                                                courseCridetsLabel)
                                                                                        .addComponent(
                                                                                                courseScheduleLabel))
                                                                                .addGap(2, 2, 2)
                                                                                .addGroup(jPanel1Layout
                                                                                        .createParallelGroup(
                                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addGroup(jPanel1Layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                        false)
                                                                                                .addComponent(
                                                                                                        courseSeatsTextField,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        45,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addComponent(
                                                                                                        courseCreditsTextField,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        1,
                                                                                                        Short.MAX_VALUE))
                                                                                        .addGroup(jPanel1Layout
                                                                                                .createSequentialGroup()
                                                                                                .addComponent(
                                                                                                        courseDayComboBox,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGap(13, 13, 13)
                                                                                                .addComponent(
                                                                                                        startHourComboBox,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addPreferredGap(
                                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                .addComponent(
                                                                                                        endHourComboBox,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                        .addComponent(courseDescriptionLabel))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        7, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(courseCodeLabel)
                                                                        .addComponent(courseNameLabel))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(courseCodeTextField,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                145, Short.MAX_VALUE)
                                                                        .addComponent(courseNameTextField))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(instructorLabel)
                                                                        .addComponent(prerequistisLabel))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)))
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(courseInstructorComboBox, 0, 170, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2))
                                                .addGap(2, 2, 2))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(24, 24, 24)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(courseCodeLabel)
                                        .addComponent(courseCodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(courseInstructorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(instructorLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(courseNameLabel)
                                                        .addComponent(courseNameTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(prerequistisLabel))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(courseSeatsLabel)
                                                        .addComponent(courseSeatsTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(courseCridetsLabel)
                                                        .addComponent(courseCreditsTextField,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 86,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(courseScheduleLabel)
                                        .addComponent(courseDayComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(startHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(endHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(courseDescriptionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addCourseButton1)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Add Course", jPanel1);

        studentTotalLabel.setText("Student Total");

        courseTotalLabel.setText("Courses Total");

        advisorsTotalLabel.setText("Advisors Total");

        studentTotalValueLabel.setText(String.valueOf(students.size()));

        courseTotalValueLabel.setText(String.valueOf(courses.size()));

        advisorsTotalValueLabel.setText(String.valueOf(advisors.size()));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(studentTotalLabel)
                                        .addComponent(studentTotalValueLabel))
                                .addGap(92, 92, 92)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(courseTotalLabel)
                                        .addComponent(courseTotalValueLabel))
                                .addGap(87, 87, 87)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(advisorsTotalLabel)
                                        .addComponent(advisorsTotalValueLabel))
                                .addGap(108, 108, 108)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentTotalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(courseTotalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(advisorsTotalValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentTotalLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(courseTotalLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(advisorsTotalLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(174, 174, 174)));

        jTabbedPane1.addTab("Statistics", jPanel3);

        userRoleLabel.setText("User Role:");

        roleComboBox.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Advisor" }));

        firstNameLabel.setText("First Name:");

        usernameLabel.setText("Username:");

        passwordLabel.setText("Password:");

        addUserButton.setText("Add User");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }

            private void addUserButtonActionPerformed(ActionEvent evt) {
                String selectedRole = (String) roleComboBox.getSelectedItem();
                String newUserName = usernameTextField.getText();
                if (selectedRole == "Student") {
                    System.out.println("Adding new student");
                    int maxStudentID = Collections
                            .max(students.stream().map(StudentTemplate::getUserID).collect(Collectors.toList())) + 1;
                    System.out.println("Max student ID is " + maxStudentID);

                    if (students.stream().anyMatch(s -> s.getUsername().equals(newUserName))) {
                        System.err.println("Student Username already exists.");
                        JOptionPane.showMessageDialog(null, "Student Username already exists.");
                    } else {
                        StudentTemplate student = new StudentTemplate(maxStudentID, newUserName,
                                passwordTextField.getText(), firstNameTextField.getText(), lastNameTextField.getText(),
                                null, null, null);

                        System.out.println("Adding student " + student.toString());
                        students.add(student);
                        JsonHandler.writeStudentsToJson(students, "src/coresy/systemdata/students.json");
                        System.out.println("Student Added Successfully.");
                        JOptionPane.showMessageDialog(null, "Student Added Successfully.");
                    }

                }
                if (selectedRole == "Advisor") {
                    int maxAdvisorID = Collections
                            .max(advisors.stream().map(AdvisorTemplate::getUserID).collect(Collectors.toList())) + 1;
                    if (advisors.stream().anyMatch(a -> a.getUsername().equals(newUserName))) {
                        JOptionPane.showMessageDialog(null, "Advisor Username already exists.");
                    } else {
                        AdvisorTemplate advisor = new AdvisorTemplate(maxAdvisorID, newUserName,
                                passwordTextField.getText(), firstNameTextField.getText(),
                                lastNameTextField.getSelectedText(), null);

                        advisors.add(advisor);
                        JsonHandler.writeAdvisorsToJson(advisors, "src/coresy/systemdata/advisors.json");
                        JOptionPane.showMessageDialog(null, "Advisor Added Successfully.");
                    }

                }
            }
        });

        lastNameLabel.setText("Last Name:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(addUserButton)
                                        .addGroup(jPanel2Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(userRoleLabel)
                                                                .addComponent(firstNameLabel))
                                                        .addGap(38, 38, 38)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(firstNameTextField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 115,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(roleComboBox,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(usernameLabel)
                                                                .addComponent(passwordLabel)
                                                                .addComponent(lastNameLabel))
                                                        .addGap(39, 39, 39)
                                                        .addGroup(jPanel2Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                .addComponent(usernameTextField,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(passwordTextField,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE, 115,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(lastNameTextField)))))
                                .addContainerGap(221, Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userRoleLabel)
                                        .addComponent(roleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(firstNameLabel)
                                        .addComponent(firstNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lastNameLabel)
                                        .addComponent(lastNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(usernameLabel)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(12, 12, 12)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordLabel)
                                        .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(addUserButton)
                                .addContainerGap(79, Short.MAX_VALUE)));

        jTabbedPane1.addTab("Add User", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCourseButton1;
    private javax.swing.JButton addUserButton;
    private javax.swing.JLabel advisorsTotalLabel;
    private javax.swing.JLabel advisorsTotalValueLabel;
    private javax.swing.JLabel courseCodeLabel;
    private javax.swing.JTextField courseCodeTextField;
    private javax.swing.JTextField courseCreditsTextField;
    private javax.swing.JLabel courseCridetsLabel;
    private javax.swing.JComboBox<String> courseDayComboBox;
    private javax.swing.JTextArea courseDesTextArea;
    private javax.swing.JLabel courseDescriptionLabel;
    private javax.swing.JComboBox<String> courseInstructorComboBox;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JTextField courseNameTextField;
    private javax.swing.JList<String> coursePrerequistisList;
    private javax.swing.JLabel courseScheduleLabel;
    private javax.swing.JLabel courseSeatsLabel;
    private javax.swing.JTextField courseSeatsTextField;
    private javax.swing.JLabel courseTotalLabel;
    private javax.swing.JLabel courseTotalValueLabel;
    private javax.swing.JComboBox<String> endHourComboBox;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel instructorLabel;
    private javax.swing.JComboBox<String> roleComboBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel prerequistisLabel;
    private javax.swing.JComboBox<String> startHourComboBox;
    private javax.swing.JLabel studentTotalLabel;
    private javax.swing.JLabel studentTotalValueLabel;
    private javax.swing.JLabel userRoleLabel;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
