package coresy.userinterface;

import java.util.List;

import javax.swing.JOptionPane;

import coresy.AdminTemplate;
import coresy.AdvisorTemplate;
import coresy.CourseTemplate;
import coresy.StudentTemplate;

public class LoginUI extends javax.swing.JFrame {

    public LoginUI(List<StudentTemplate> students, List<AdvisorTemplate> advisors, List<AdminTemplate> admins,
            List<CourseTemplate> courses) {
        initComponents(students, advisors, admins, courses);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents(List<StudentTemplate> students, List<AdvisorTemplate> advisors,
            List<AdminTemplate> admins, List<CourseTemplate> courses) {

        userSelectionbuttonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        studentRadioButton = new javax.swing.JRadioButton();
        advisorRadioButton = new javax.swing.JRadioButton();
        adminRadioButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTextField = new javax.swing.JTextField();
        userPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userSelectionbuttonGroup.add(studentRadioButton);
        studentRadioButton.setText("Student");

        userSelectionbuttonGroup.add(advisorRadioButton);
        advisorRadioButton.setText("Advisor");

        userSelectionbuttonGroup.add(adminRadioButton);
        adminRadioButton.setText("Admin");

        jLabel1.setText("Login as:");

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt, students, advisors, admins, courses);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(studentRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(advisorRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(adminRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(96, 96, 96))
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER, false)
                                                .addComponent(usernameTextField)
                                                .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(studentRadioButton)
                                        .addComponent(advisorRadioButton)
                                        .addComponent(adminRadioButton))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(usernameTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(userPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addComponent(loginButton)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(
            java.awt.event.ActionEvent evt,
            List<StudentTemplate> students,
            List<AdvisorTemplate> advisors,
            List<AdminTemplate> admins,
            List<CourseTemplate> courses) {// GEN-FIRST:event_loginButtonActionPerformed
        if (userSelectionbuttonGroup.getSelection() != null) {
            boolean userFound = false;
            if (studentRadioButton.isSelected()) {
                for (StudentTemplate std : students) {
                    if (usernameTextField.getText().equals(std.getUsername()) &&
                            new String(userPasswordField.getPassword()).equals(std.getPassword())) {
                        new StudentUI(std, students, advisors, courses).setVisible(true);
                        dispose();
                        userFound = true;
                        break;
                    }
                }
            } else if (advisorRadioButton.isSelected()) {
                for (AdvisorTemplate adv : advisors) {
                    if (usernameTextField.getText().equals(adv.getUsername()) &&
                            new String(userPasswordField.getPassword()).equals(adv.getPassword())) {
                        new AdvisorUI(adv, students, advisors, courses).setVisible(true);
                        dispose();
                        userFound = true;
                        break;
                    }
                }
            } else if (adminRadioButton.isSelected()) {
                for (AdminTemplate adm : admins) {
                    if (usernameTextField.getText().equals(adm.getUsername()) &&
                            new String(userPasswordField.getPassword()).equals(adm.getPassword())) {
                        new AdminUI(adm, students, advisors, courses).setVisible(true);
                        dispose();
                        userFound = true;
                        break;
                    }
                }
            }
            if (!userFound) {
                JOptionPane.showMessageDialog(null, "Username or password is incorrect");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a role to login");
        }
    }// GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    /**/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton adminRadioButton;
    private javax.swing.JRadioButton advisorRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JRadioButton studentRadioButton;
    private javax.swing.JPasswordField userPasswordField;
    private javax.swing.ButtonGroup userSelectionbuttonGroup;
    private javax.swing.JTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
